### ISSUE TITLE
customizing/resizing the actual bar width

### ISSUE THREAD

**Issue by alexge233** [creaktive/rainbarf#26]
Hi, is it possible to customise or set the width for CPU/RAM/SWAP manually?
My tmux shows a huge chart for RAM/SWAP (I have 12Gb Ram and 30Gb swap) and a tiny only chart for the rest:

![screenshot from 2015-12-18 19 58 25](https://cloud.githubusercontent.com/assets/6159747/11906040/c73fa168-a5c1-11e5-8d4e-0359a165474b.png)

**Comment by creaktive** [comment]
Try running `rainbarf --width 20` and see how it renders outside of tmux. Concerning swap: only *used* swap memory is represented, precisely because of the cases when one's system has much more swap than RAM :)
