### ISSUE TITLE
rainbarf fails in macOS sandbox during Homebrew CI

### ISSUE THREAD

**Issue by ilovezfs** [creaktive/rainbarf#31]
I can avoid this by passing `--help`, but a regular invocation without options leads to

```
iMac-TMP:rainbarf joe$ brew test -v rainbarf
Testing rainbarf
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160906-26936-h2bs95.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/rainbarf.rb -v --HEAD
==> /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf
Can't exec "/usr/bin/top": Operation not permitted at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 243.
Use of uninitialized value $top{"cpu_usage"} in split at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 306.
Use of uninitialized value $usage{"idle"} in division (/) at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 308.
Use of uninitialized value $top{"physmem"} in pattern match (m//) at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 315.
Use of uninitialized value $top{"physmem"} in split at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 318.
Use of uninitialized value in division (/) at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 99.
Illegal division by zero at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 99.
==> Sandbox log
Sep  6 02:44:20 sandboxd[140]: perl5.18(26945) deny forbidden-exec-sugid
Error: rainbarf: failed
Failed executing: /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf 
/usr/local/Library/Homebrew/formula.rb:1597:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1534:in `open'
/usr/local/Library/Homebrew/formula.rb:1534:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/rainbarf.rb:22:in `block in <class:Rainbarf>'
/usr/local/Library/Homebrew/formula.rb:1435:in `block (2 levels) in run_test'
/usr/local/Library/Homebrew/formula.rb:764:in `with_logging'
/usr/local/Library/Homebrew/formula.rb:1434:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1428:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by creaktive** [comment]
This happens because homebrew's sandbox forbids access to the `top` utility:

```
Can't exec "/usr/bin/top": Operation not permitted at /usr/local/Cellar/rainbarf/HEAD-a574fad/bin/rainbarf line 243.
```

`rainbarf` can't be tested without `top`, and there's no situation (except with homebrew sandbox) when `top` is unavailable. Maybe it is possible to whitelist `top` & `ioreg` for homebrew recipes? However quick Google search yielded nothing for me :(

**Comment by ilovezfs** [comment]
We can of course just keep using `--help` for the test, but in general you could probably check
```
bash-3.2$ top -h
bash: /usr/bin/top: Operation not permitted
bash-3.2$ echo $?
126
```
and then do something to avoid the crash scenario.

**Comment by creaktive** [comment]
I have a good example how harmful this could be. Suppose Apple updates `/usr/bin/top` utility and changes the output format. A simple test such as one involving `--help` would still pass, but `rainbarf` itself would be completely broken! Now, notice that `rainbarf` also have it's own tests with quite a decent coverage, you can try this:
```
bash-3.2$ cd rainbarf/
bash-3.2$ prove
t/00-compile.t .................. ok
t/01-tmux.t ..................... ok
...
All tests successful.
Files=18, Tests=21, 13 wallclock secs ( 0.06 usr  0.04 sys +  1.13 cusr  1.54 csys =  2.77 CPU)
Result: PASS
```
We already run the testing suite on variety of platforms: http://matrix.cpantesters.org/?dist=App-rainbarf+1.4
And also on TravisCI: https://travis-ci.org/creaktive/rainbarf
So it's only a matter of a proper sandbox configuration.

**Comment by ilovezfs** [comment]
My point was simply that you should catch the permissions error and handle it gracefully rather than letting the program die in an illegal division by zero.

**Comment by creaktive** [comment]
Thing is, I already do the permissions check for all the external utilities :)
This ~~feature~~bug doesn't belong to `rainbarf`, it's a homebrew or `sandbox-exec` thing.

**Comment by ilovezfs** [comment]
If you think it's ok for your program to crash, I think we have different ideas about software development.

**Comment by creaktive** [comment]
Your suggestion is to check if a given external utility is indeed available
and if not, recover gracefully. This is already done since the very first
version. Still fails under the homebrew sandbox. I have no idea why. Pull
requests are very welcome :)
