### ISSUE TITLE
No values in the output 

### ISSUE THREAD

**Issue by asvc** [creaktive/rainbarf#32]
Works just fine elsewhere.

```
Debian 9.3
Linux 4.9.0-4-amd64
tmux 2.6  
bash 4.4.12  
latest rainbarf installed from CPAN  
```

Output of `rainbarf --screen`:

`{gg}▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁{rr}▁{yy}▁▁▁▁▁▁{bb}▁▁▁▁{cc}{= dd}`

Output stays the same irrespective of load/cpu/mem usage and battery status.
Tried various combinations of parameters, but without much of success.

**Comment by creaktive** [comment]
Does this issue still persist?
