### ISSUE TITLE
Rainbarf appears to be adding a newline in Tmux

### ISSUE THREAD

**Issue by alexge233** [creaktive/rainbarf#34]
This has happened recently and can only attribute to some update. It only happens in OSX so far, and what I get is a newline is added every time I press [ENTER] regardless of UI interaction.
See example below.

![Screenshot 2019-04-08 at 09 31 56](https://user-images.githubusercontent.com/6159747/55710605-e4f12280-59e2-11e9-8f5b-1f4f7966b7d0.png)

**Comment by creaktive** [comment]
I'm sure rainbarf is not the responsible for this! If it was, you'd have a line break _before_ the `fish` thingie to the right of rainbarf...

**Comment by alexge233** [comment]
Apologies then, I guess OSX has changed something with the update!

**Comment by ea2809** [comment]
@alexge233 could you fix this behavior? I have the same problem, without it tmux is perfect, with rainbarf it adds new lines.

**Comment by alexge233** [comment]
@ea2809 no I didn't manage to fix it!!!

**Comment by usptact** [comment]
I had the very same issue in MacOS Catalina 10.15.7. My ~/.rainbarf.conf looked like this
```
width=20
bolt
remaining
rgb
```
The newlines were caused by the "bolt" option. I removed it and newlines stopped being added.

**Comment by creaktive** [comment]
I did some investigation; it seems that the issue is that `tmux` gets confused with the length of the multibyte strings (and ⚡️ *is* a multibyte character). The only reliable workaround is *not* using the `bolt` option, unfortunately :(
